/* automatically generated by rust-bindgen 0.69.5 */

pub const _FENV_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 0;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 0;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 42;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const FE_INEXACT: u32 = 65536;
pub const FE_UNDERFLOW: u32 = 131072;
pub const FE_OVERFLOW: u32 = 262144;
pub const FE_DIVBYZERO: u32 = 524288;
pub const FE_INVALID: u32 = 1048576;
pub const FE_ALL_EXCEPT: u32 = 2031616;
pub const FE_TONEAREST: u32 = 0;
pub const FE_TOWARDZERO: u32 = 256;
pub const FE_UPWARD: u32 = 512;
pub const FE_DOWNWARD: u32 = 768;
pub mod _bindgen_ty_1 {
    pub type Type = ::core::ffi::c_uint;
    pub const FE_INEXACT: Type = 65536;
    pub const FE_UNDERFLOW: Type = 131072;
    pub const FE_OVERFLOW: Type = 262144;
    pub const FE_DIVBYZERO: Type = 524288;
    pub const FE_INVALID: Type = 1048576;
}
pub mod _bindgen_ty_2 {
    pub type Type = ::core::ffi::c_uint;
    pub const FE_TONEAREST: Type = 0;
    pub const FE_TOWARDZERO: Type = 256;
    pub const FE_UPWARD: Type = 512;
    pub const FE_DOWNWARD: Type = 768;
}
pub type fexcept_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fenv_t {
    pub __fp_control_register: ::core::ffi::c_uint,
}
#[test]
fn bindgen_test_layout_fenv_t() {
    const UNINIT: ::core::mem::MaybeUninit<fenv_t> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<fenv_t>(),
        4usize,
        concat!("Size of: ", stringify!(fenv_t))
    );
    assert_eq!(
        ::core::mem::align_of::<fenv_t>(),
        4usize,
        concat!("Alignment of ", stringify!(fenv_t))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).__fp_control_register) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(fenv_t),
            "::",
            stringify!(__fp_control_register)
        )
    );
}
extern "C" {
    pub fn feclearexcept(__excepts: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn fegetexceptflag(
        __flagp: *mut fexcept_t,
        __excepts: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
    pub fn feraiseexcept(__excepts: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn fesetexceptflag(
        __flagp: *const fexcept_t,
        __excepts: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
    pub fn fetestexcept(__excepts: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn fegetround() -> ::core::ffi::c_int;
    pub fn fesetround(__rounding_direction: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn fegetenv(__envp: *mut fenv_t) -> ::core::ffi::c_int;
    pub fn feholdexcept(__envp: *mut fenv_t) -> ::core::ffi::c_int;
    pub fn fesetenv(__envp: *const fenv_t) -> ::core::ffi::c_int;
    pub fn feupdateenv(__envp: *const fenv_t) -> ::core::ffi::c_int;
}
